# Case 1: β⁻=10, β⁺=1 (Standard MMS Verification)
# Only overrides from default.yaml are listed here.

beta_minus: 10.0
beta_plus: 1.0

# resolution: 16
# resolution: 24
# resolution: 32
resolution: 64

num_layers: 2
epochs: 1000

# save_dir: ./results/case1/beta-m-p-10-1-r-16
# save_dir: ./results/case1/beta-m-p-10-1-r-24
# save_dir: ./results/case1/beta-m-p-10-1-r-32
save_dir: ./results/case1/beta-m-p-10-1-r-64
